title: Eliza Marie Henry Mullins # your name (or website title) here
logo: "/images/HenryMullins.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Entry-Level Geospatial Specialist, and member of the Army Reserve, with 3 years of experience in Geospatial Analysis and 7+ years of managing security functions and diverse cross-functional teams. Innovative leader and skillful solutions planner focused on continuous improvement. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/eliza-mullins-5a6a8039/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
